server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心获取创建动态路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route     #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service      #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**             # 断言，路径相匹配的进行路由
            - After=2022-07-01T16:12:21.672+08:00[Asia/Shanghai] #这个时间之后可以访问
          #  - Between=2022-07-01T16:12:21.672+08:00[Asia/Shanghai],2022-07-01T16:16:21.672+08:00[Asia/Shanghai]  #这个时间段以外不能访问呢
            - Cookie=username,song
            - Header=X-Request-Id, \d+         # 请求头要有X-Request-Id属性并且值为整数

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service      #匹配后提供服务的路由地址
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/lb/**              # 断言，路径相匹配的进行路由
            - Before=2023-07-01T16:12:21.672+08:00[Asia/Shanghai] #这个时间之前可以访问

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
